### ISSUE TITLE
TreeView LoadChildren not working (Uncaught TypeError: matcher is not a function)

### ISSUE THREAD

**Issue by martinsura** [riganti/dotvvm#602]
BusinessPack TreeView

Setup by  https://www.dotvvm.com/docs/controls/businesspack/TreeView/latest (Sample 6: Lazy loading of children)

Got error

dotvvm--internal:613 Uncaught TypeError: matcher is not a function
    at DotvvmSerialization.findObject (dotvvm--internal:613)
    at DotvvmSerialization.serialize (dotvvm--internal:556)
    at DotvvmSerialization.serialize (dotvvm--internal:519)
    at DotvvmSerialization.serialize (dotvvm--internal:568)
    at DotVVM.staticCommandPostback (dotvvm--internal:1257)
    at eval (eval at parseBindingsString (knockout:70), <anonymous>:3:520)
    at HTMLDivElement.eval (eval at parseBindingsString (knockout:70), <anonymous>:3:750)
    at n.expandItem (dotvvm--businesspack:1)
    at n.onExpandClick (dotvvm--businesspack:1)
    at HTMLDivElement.dispatch (jquery-3.2.1.js:5206)

Dotvvm version: 1.1.9.0
Bootstrap control version 1.1.2.0
BusinessPack component version 1.1.8.0

Owin project version

.net framework 4.7.1

**Comment by djanosik** [comment]
It looks it's fixed in 2.0. @exyi Do you know when `pathMatcher` is `null`?

**Comment by martinsura** [comment]
It works on BusinessPack version 1.1.9.0.
