### ISSUE TITLE
FirstOrDefault/Where().FirstOrDefault() with property-comparing predicate broken in JS translation (v5) — regression of #1870/#1871

### ISSUE THREAD

**Issue by LiborDrmots** [riganti/dotvvm#2105]
### Describe
Client-side (knockout) JS translation of a value binding using FirstOrDefault with a predicate that compares an item property to a value, followed by a member access, fails at runtime. This looks like a regression of the same class of bug fixed in #1870 / #1871 (ko.unwrap handling in Linq translations for First/Last/ElementAt), reappearing in v5.

Two variants of the expression fail, each with a different error:
**Variant A** — FirstOrDefault(predicate)
`{{value: _control.DostupnaRazeni.FirstOrDefault(f=>f.KlicRazeni == "").PopisRazeni}}`
Error:
`$control.DostupnaRazeni(...)?.find(...) is not a function`

**Variant B** — Where(predicate).FirstOrDefault()
`{{value: _control.DostupnaRazeni.Where(f=>f.KlicRazeni == "").FirstOrDefault().PopisRazeni}}`
Error:
`Unable to process binding "text: function(){return (() =>{
	let a;
	return((a = $control.DostupnaRazeni()?.filter((f) => ko.unwrap(f).KlicRazeni() =="")) && a[0]())?.PopisRazeni;})() }"
Message: a[0] is not a function`

Here a[0] is the found item — a plain mapped object with observable properties (the same shape as f inside the predicate, which is correctly unwrapped via ko.unwrap(f)). Instead of reading a[0]'s PopisRazeni observable member, the translator calls a[0] directly as a function, which throws.

### What works
`{{value: _control.DostupnaRazeni.FirstOrDefault().PopisRazeni}}
{{value: _control.DostupnaRazeni.FirstOrDefault(f=>true).PopisRazeni}}`

So the bug is specifically triggered once the predicate contains a property comparison (f.KlicRazeni == "...") rather than a trivial/constant predicate — this points to a different (broken) translator code path being used depending on predicate complexity, and it affects both the FirstOrDefault(predicate) overload and the Where(predicate).FirstOrDefault() chain.

**Expected behavior**
The found item should be read as a[0]?.PopisRazeni() (or ko.unwrap(a[0])?.PopisRazeni), consistent with how f is unwrapped inside the predicate — not called as a function itself.

### Environment
DotVVM version: 5.0.1 (migrated from 4.3.x, where the equivalent binding worked)
Related: #1870, #1871
